# Generated by Django 4.0.5 on 2022-06-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_candidatos_pretensao_alter_candidatos_vaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='previsao',
            field=models.DateField(null=True),
        ),
    ]
