# Generated by Django 4.0.5 on 2022-06-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_candidatos_area_vagas_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='pretensao',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
