# Generated by Django 4.0.5 on 2022-06-27 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_candidatos_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='area',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatos_area', to='app.vagas'),
        ),
    ]
