# Generated by Django 4.0.5 on 2022-06-27 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_candidatos_vaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatos',
            name='vaga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidato_vaga', to='app.vagas'),
        ),
    ]
