# Generated by Django 4.0.5 on 2022-06-28 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='areas_vagas', to='app.areas'),
        ),
    ]
