# Generated by Django 4.0.5 on 2022-06-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_indicacaomodel_alter_candidatos_indicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatos',
            name='indicador',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
