# Generated by Django 4.0.5 on 2022-07-06 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_colaboradores'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradores',
            name='modalidade_contratacao',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='regras_ferias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimo_dias', models.DurationField(blank=True, null=True)),
                ('tempo_max', models.DurationField(blank=True, null=True)),
                ('periodo', models.DurationField(blank=True, null=True)),
                ('modalidade_contratacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicacao', to='app.colaboradores')),
            ],
        ),
    ]
