# Generated by Django 4.0.5 on 2022-07-11 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_regras_ferias_modalidade_contratacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regras_ferias',
            name='modalidade_contratada',
        ),
        migrations.AddField(
            model_name='regras_ferias',
            name='modalidade_contratacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modalidade_colaborador', to='app.modalidades'),
        ),
    ]
