# Generated by Django 4.0.5 on 2022-07-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_regras_ferias_modalidade_contratada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefinirFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.IntegerField(max_length=150)),
                ('data_retorno', models.IntegerField(max_length=150)),
            ],
        ),
    ]
