# Generated by Django 4.0.5 on 2022-07-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_tiposferias_colaboradores_dias_acumulados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='dias_acumulados',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='periodo',
            field=models.IntegerField(null=True),
        ),
    ]
