# Generated by Django 4.0.5 on 2022-07-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_colaboradores_dias_acumulados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='dias_acumulados',
            field=models.IntegerField(null=True),
        ),
    ]
