# Generated by Django 4.0.5 on 2022-07-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_colaboradores_dias_acumulados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='data_inicio',
            field=models.DateTimeField(),
        ),
    ]
