# Generated by Django 4.0.5 on 2022-07-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_remove_colaboradores_dias_acumulados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definirferias',
            name='data_retorno',
            field=models.DateField(blank=True, verbose_name='%d/%m/%Y'),
        ),
        migrations.AlterField(
            model_name='definirferias',
            name='data_saida',
            field=models.DateField(blank=True, verbose_name='%d/%m/%Y'),
        ),
    ]
